# docker-compose up -d
# docker compose up --scale cleaning-service=6
# docker compose down

version: "3.8"

services:
  booking-service:
    image: booking-service:latest
    env_file:
      - ../booking-service/booking-service/.env
    ports:
        - "8000"
    depends_on:
      - booking-db
    deploy:
      replicas: 1

  cleaning-service:
    image: cleaning-service:latest
    env_file:
      - ../cleaning-service/cleaning-service/.env
    ports:
      - "8001"
    depends_on:
      - cleaning-db
    deploy:
      replicas: 3

  dining-service:
    image: dining-service:latest
    env_file:
      - ../dining-service/dining-service/.env
    ports:
      - "8002"
    depends_on:
      - dining-db
    deploy:
      replicas: 4

  accounting-service:
    image: accounting-service:latest
    env_file:
      - ../accounting-service/accounting-service/.env
    ports:
      - "8003"
    depends_on:
      - accounting-db
    deploy:
      replicas: 2

  notification-service:
    image: notification-service:latest
    env_file:
      - ../notification-service/notification-service/.env
    ports:
      - "8004"
    depends_on:
      - notification-db
    deploy:
      replicas: 2

  booking-db:
    image: postgres:15
    container_name: booking_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking_db
    ports:
      - "5433:5432"  # Host port 5433 → Container port 5432
    volumes:
      - booking_data:/var/lib/postgresql/data


  cleaning-db:
    image: postgres:15
    container_name: cleaning_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleaning_db
    ports:
      - "5434:5432"  # Host port 5434 → Container port 5432
    volumes:
      - cleaning_data:/var/lib/postgresql/data


  dining-db:
    image: postgres:15
    container_name: dining_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dining_db
    ports:
      - "5435:5432"  # Host port 5435 → Container port 5432
    volumes:
      - dining_data:/var/lib/postgresql/data

  accounting-db:
    image: postgres:15
    container_name: accounting_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounting_db
    ports:
      - "5436:5432"  # Host port 5436 → Container port 5432
    volumes:
      - accounting_data:/var/lib/postgresql/data

  notification-db:
    image: postgres:15
    container_name: notification_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_db
    ports:
      - "5437:5432"  # Host port 5437 → Container port 5432
    volumes:
      - notification_data:/var/lib/postgresql/data

volumes:
  booking_data:
  cleaning_data:
  dining_data:
  accounting_data:
  notification_data:

